package com.hunt.otziv.payments.dto;

import com.hunt.otziv.payments.model.ManualPaymentType;
import com.hunt.otziv.payments.model.PaymentMethod;
import java.math.BigDecimal;
import java.time.LocalDateTime;

public record AdminPaymentLinkResponse(
        Long id,
        String token,
        String publicUrl,
        Long orderId,
        String companyTitle,
        String filialTitle,
        String description,
        BigDecimal amount,
        long amountKopecks,
        Long reservedAmountKopecks,
        Long confirmedAmountKopecks,
        String status,
        String paymentMethod,
        String paymentProfileCode,
        String paymentProfileName,
        String manualSource,
        Long manualTaskId,
        String manualTaskTitle,
        String tbankTerminalKey,
        String tbankPaymentId,
        String tbankOrderId,
        String payerEmail,
        String paymentUrl,
        String manualPaymentType,
        String manualPhone,
        String manualRecipientName,
        String manualPaymentUrl,
        String manualPaymentButtonLabel,
        String manualComment,
        LocalDateTime manualReportedAt,
        String manualConfirmedBy,
        LocalDateTime manualConfirmedAt,
        String receiptStatus,
        LocalDateTime paymentSuccessNotifiedAt,
        String paymentSuccessNotificationError,
        String clientChatPlatform,
        boolean clientChatReady,
        String clientChatWarning,
        String lastError,
        LocalDateTime createdAt,
        LocalDateTime updatedAt,
        LocalDateTime expiresAt,
        LocalDateTime initiatedAt,
        LocalDateTime paidAt,
        LocalDateTime sbpQrCreatedAt,
        boolean archived,
        LocalDateTime archivedAt,
        String archiveReason,
        boolean refundable
) {
}
