CREATE TABLE IF NOT EXISTS manager_site_activity_events (
    activity_id BIGINT NOT NULL AUTO_INCREMENT,
    user_id BIGINT NOT NULL,
    manager_id BIGINT NULL,
    occurred_at DATETIME(6) NOT NULL,
    activity_type VARCHAR(32) NOT NULL,
    route VARCHAR(500) NULL,
    session_id VARCHAR(80) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (activity_id),
    INDEX idx_manager_site_activity_user_time (user_id, occurred_at),
    INDEX idx_manager_site_activity_manager_time (manager_id, occurred_at),
    INDEX idx_manager_site_activity_created (created_at),
    CONSTRAINT fk_manager_site_activity_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_manager_site_activity_manager FOREIGN KEY (manager_id) REFERENCES managers (manager_id)
);

CREATE TABLE IF NOT EXISTS manager_performance_daily (
    daily_id BIGINT NOT NULL AUTO_INCREMENT,
    summary_date DATE NOT NULL,
    manager_id BIGINT NOT NULL,
    manager_user_id BIGINT NULL,
    manager_name VARCHAR(220) NULL,
    base_score INT NOT NULL DEFAULT 0,
    adjusted_score INT NOT NULL DEFAULT 0,
    grade VARCHAR(4) NOT NULL DEFAULT 'J',
    formula_version VARCHAR(40) NOT NULL DEFAULT 'manager-v2',
    task_total BIGINT NOT NULL DEFAULT 0,
    task_completed BIGINT NOT NULL DEFAULT 0,
    task_open BIGINT NOT NULL DEFAULT 0,
    task_progress_percent DECIMAL(5,2) NOT NULL DEFAULT 0,
    overdue_count BIGINT NOT NULL DEFAULT 0,
    risk_count BIGINT NOT NULL DEFAULT 0,
    unanswered_count BIGINT NOT NULL DEFAULT 0,
    first_reply_count BIGINT NOT NULL DEFAULT 0,
    first_reply_total_seconds BIGINT NOT NULL DEFAULT 0,
    first_reply_average_seconds BIGINT NOT NULL DEFAULT 0,
    first_reply_median_seconds BIGINT NOT NULL DEFAULT 0,
    first_reply_p90_seconds BIGINT NOT NULL DEFAULT 0,
    all_reply_count BIGINT NOT NULL DEFAULT 0,
    all_reply_total_seconds BIGINT NOT NULL DEFAULT 0,
    all_reply_average_seconds BIGINT NOT NULL DEFAULT 0,
    all_reply_median_seconds BIGINT NOT NULL DEFAULT 0,
    all_reply_p90_seconds BIGINT NOT NULL DEFAULT 0,
    replies_in_sla BIGINT NOT NULL DEFAULT 0,
    reply_histogram VARCHAR(500) NULL,
    problem_count BIGINT NOT NULL DEFAULT 0,
    problem_resolved_count BIGINT NOT NULL DEFAULT 0,
    problem_resolution_total_seconds BIGINT NOT NULL DEFAULT 0,
    problem_resolution_average_seconds BIGINT NOT NULL DEFAULT 0,
    site_active_seconds BIGINT NOT NULL DEFAULT 0,
    messenger_active_seconds BIGINT NOT NULL DEFAULT 0,
    confirmed_active_seconds BIGINT NOT NULL DEFAULT 0,
    aggregation_status VARCHAR(24) NOT NULL DEFAULT 'CALCULATED',
    finalized_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (daily_id),
    UNIQUE KEY uk_manager_performance_daily (summary_date, manager_id),
    INDEX idx_manager_performance_daily_manager_date (manager_id, summary_date),
    INDEX idx_manager_performance_daily_status_date (aggregation_status, summary_date),
    CONSTRAINT fk_manager_performance_daily_manager FOREIGN KEY (manager_id) REFERENCES managers (manager_id)
);

CREATE TABLE IF NOT EXISTS manager_performance_monthly (
    monthly_id BIGINT NOT NULL AUTO_INCREMENT,
    month_start DATE NOT NULL,
    manager_id BIGINT NOT NULL,
    manager_user_id BIGINT NULL,
    working_days INT NOT NULL DEFAULT 0,
    score_sum BIGINT NOT NULL DEFAULT 0,
    average_score DECIMAL(5,2) NOT NULL DEFAULT 0,
    closing_score INT NOT NULL DEFAULT 0,
    closing_grade VARCHAR(4) NOT NULL DEFAULT 'J',
    task_total BIGINT NOT NULL DEFAULT 0,
    task_completed BIGINT NOT NULL DEFAULT 0,
    reply_count BIGINT NOT NULL DEFAULT 0,
    reply_total_seconds BIGINT NOT NULL DEFAULT 0,
    replies_in_sla BIGINT NOT NULL DEFAULT 0,
    reply_histogram VARCHAR(500) NULL,
    problem_count BIGINT NOT NULL DEFAULT 0,
    problem_resolved_count BIGINT NOT NULL DEFAULT 0,
    problem_resolution_total_seconds BIGINT NOT NULL DEFAULT 0,
    site_active_seconds BIGINT NOT NULL DEFAULT 0,
    messenger_active_seconds BIGINT NOT NULL DEFAULT 0,
    confirmed_active_seconds BIGINT NOT NULL DEFAULT 0,
    strong_days INT NOT NULL DEFAULT 0,
    formula_version VARCHAR(40) NOT NULL DEFAULT 'manager-v2',
    closed_period BIT NOT NULL DEFAULT 0,
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (monthly_id),
    UNIQUE KEY uk_manager_performance_monthly (month_start, manager_id),
    INDEX idx_manager_performance_monthly_manager (manager_id, month_start),
    CONSTRAINT fk_manager_performance_monthly_manager FOREIGN KEY (manager_id) REFERENCES managers (manager_id)
);

CREATE TABLE IF NOT EXISTS manager_performance_yearly (
    yearly_id BIGINT NOT NULL AUTO_INCREMENT,
    year_start DATE NOT NULL,
    manager_id BIGINT NOT NULL,
    manager_user_id BIGINT NULL,
    working_days INT NOT NULL DEFAULT 0,
    score_sum BIGINT NOT NULL DEFAULT 0,
    average_score DECIMAL(5,2) NOT NULL DEFAULT 0,
    closing_score INT NOT NULL DEFAULT 0,
    closing_grade VARCHAR(4) NOT NULL DEFAULT 'J',
    task_total BIGINT NOT NULL DEFAULT 0,
    task_completed BIGINT NOT NULL DEFAULT 0,
    reply_count BIGINT NOT NULL DEFAULT 0,
    reply_total_seconds BIGINT NOT NULL DEFAULT 0,
    replies_in_sla BIGINT NOT NULL DEFAULT 0,
    reply_histogram VARCHAR(500) NULL,
    problem_count BIGINT NOT NULL DEFAULT 0,
    problem_resolved_count BIGINT NOT NULL DEFAULT 0,
    problem_resolution_total_seconds BIGINT NOT NULL DEFAULT 0,
    site_active_seconds BIGINT NOT NULL DEFAULT 0,
    messenger_active_seconds BIGINT NOT NULL DEFAULT 0,
    confirmed_active_seconds BIGINT NOT NULL DEFAULT 0,
    strong_days INT NOT NULL DEFAULT 0,
    formula_version VARCHAR(40) NOT NULL DEFAULT 'manager-v2',
    closed_period BIT NOT NULL DEFAULT 0,
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (yearly_id),
    UNIQUE KEY uk_manager_performance_yearly (year_start, manager_id),
    INDEX idx_manager_performance_yearly_manager (manager_id, year_start),
    CONSTRAINT fk_manager_performance_yearly_manager FOREIGN KEY (manager_id) REFERENCES managers (manager_id)
);

CREATE TABLE IF NOT EXISTS manager_summary_delivery_log (
    delivery_id BIGINT NOT NULL AUTO_INCREMENT,
    summary_date DATE NOT NULL,
    recipient_user_id BIGINT NOT NULL,
    recipient_chat_id BIGINT NOT NULL,
    channel VARCHAR(24) NOT NULL DEFAULT 'TELEGRAM',
    status VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    attempt_count INT NOT NULL DEFAULT 0,
    error_message VARCHAR(1000) NULL,
    sent_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (delivery_id),
    UNIQUE KEY uk_manager_summary_delivery (summary_date, recipient_user_id, channel),
    INDEX idx_manager_summary_delivery_status (status, summary_date),
    INDEX idx_manager_summary_delivery_created (created_at),
    CONSTRAINT fk_manager_summary_delivery_user FOREIGN KEY (recipient_user_id) REFERENCES users (id)
);

INSERT INTO app_settings (setting_key, setting_value, updated_at) VALUES
    ('manager.summary.enabled', 'false', CURRENT_TIMESTAMP(6)),
    ('manager.summary.recipients', 'ADMIN,OWNER', CURRENT_TIMESTAMP(6)),
    ('manager.summary.recipient-user-ids', '', CURRENT_TIMESTAMP(6)),
    ('manager.summary.manager-groups-enabled', 'false', CURRENT_TIMESTAMP(6)),
    ('manager.summary.zone', 'Asia/Irkutsk', CURRENT_TIMESTAMP(6)),
    ('manager.summary.activity-idle-minutes', '15', CURRENT_TIMESTAMP(6)),
    ('manager.summary.workday-start', '09:00', CURRENT_TIMESTAMP(6)),
    ('manager.summary.workday-end', '23:00', CURRENT_TIMESTAMP(6)),
    ('manager.summary.working-days', '1,2,3,4,5,6', CURRENT_TIMESTAMP(6)),
    ('manager.summary.raw-retention-days', '90', CURRENT_TIMESTAMP(6)),
    ('manager.summary.delivery-retention-days', '180', CURRENT_TIMESTAMP(6)),
    ('manager.summary.message-text-retention-days', '30', CURRENT_TIMESTAMP(6)),
    ('manager.summary.cleanup-enabled', 'false', CURRENT_TIMESTAMP(6))
ON DUPLICATE KEY UPDATE setting_key = VALUES(setting_key);
