CREATE TABLE IF NOT EXISTS gamification_events (
    id BIGINT NOT NULL AUTO_INCREMENT,
    event_type VARCHAR(80) NOT NULL,
    actor_user_id BIGINT NULL,
    actor_role VARCHAR(40) NULL,
    actor_name VARCHAR(180) NULL,
    order_id BIGINT NULL,
    review_id BIGINT NULL,
    bad_review_task_id BIGINT NULL,
    recovery_task_id BIGINT NULL,
    worker_id BIGINT NULL,
    manager_id BIGINT NULL,
    company_id BIGINT NULL,
    company_title VARCHAR(255) NULL,
    source VARCHAR(120) NULL,
    unique_event_key VARCHAR(190) NULL,
    payload VARCHAR(1000) NULL,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_gamification_events_unique_key (unique_event_key),
    KEY idx_gamification_events_created_at (created_at),
    KEY idx_gamification_events_event_type (event_type),
    KEY idx_gamification_events_actor_user_id (actor_user_id),
    KEY idx_gamification_events_order_id (order_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
