CREATE TABLE contractor_actual_payment_attributions (
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    attribution_key VARCHAR(160) NOT NULL,
    source_kind VARCHAR(32) NOT NULL,
    source_id BIGINT NOT NULL,
    evidence_id BIGINT NULL,
    order_id BIGINT NULL,
    common_invoice_id BIGINT NULL,
    original_allocation_id BIGINT NULL,
    client_facing_allocation_id BIGINT NULL,
    accounting_mode VARCHAR(16) NOT NULL,
    original_recipient_type VARCHAR(24) NOT NULL,
    original_recipient_profile_id BIGINT NULL,
    original_recipient_user_id BIGINT NULL,
    original_recipient_name_snapshot TEXT NULL,
    actual_recipient_type VARCHAR(24) NOT NULL,
    actual_recipient_profile_id BIGINT NULL,
    actual_recipient_user_id BIGINT NULL,
    actual_recipient_name_snapshot TEXT NULL,
    current_worker_id BIGINT NULL,
    current_manager_id BIGINT NULL,
    amount_kopecks BIGINT NOT NULL,
    available_before_kopecks BIGINT NULL,
    projected_overrun_kopecks BIGINT NOT NULL DEFAULT 0,
    effective_at DATETIME(6) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    evidence_reference VARCHAR(160) NOT NULL,
    receipt_url TEXT NULL,
    actor VARCHAR(150) NOT NULL,
    correction_of_id BIGINT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    CONSTRAINT uk_contractor_actual_payment_attribution_key UNIQUE (attribution_key),
    INDEX idx_contractor_actual_payment_source (source_kind, source_id, effective_at, id),
    INDEX idx_contractor_actual_payment_evidence (evidence_id),
    INDEX idx_contractor_actual_payment_actual_profile (actual_recipient_profile_id, accounting_mode, id),
    INDEX idx_contractor_actual_payment_original_allocation (original_allocation_id),
    INDEX idx_contractor_actual_payment_client_allocation (client_facing_allocation_id),
    INDEX idx_contractor_actual_payment_correction (correction_of_id)
) ENGINE=InnoDB;

ALTER TABLE contractor_payment_allocations
    MODIFY COLUMN recipient_name_snapshot TEXT NULL;

ALTER TABLE payment_links
    ADD COLUMN manual_actual_accounting_mode VARCHAR(16) NULL,
    ADD COLUMN manual_actual_original_allocation_id BIGINT NULL,
    ADD COLUMN manual_actual_client_facing_allocation_id BIGINT NULL,
    ADD COLUMN manual_actual_original_recipient_type VARCHAR(24) NULL,
    ADD COLUMN manual_actual_original_recipient_profile_id BIGINT NULL,
    ADD COLUMN manual_actual_original_recipient_user_id BIGINT NULL,
    ADD COLUMN manual_actual_original_recipient_name_snapshot TEXT NULL,
    ADD COLUMN manual_actual_recipient_type VARCHAR(24) NULL,
    ADD COLUMN manual_actual_recipient_profile_id BIGINT NULL,
    ADD COLUMN manual_actual_recipient_user_id BIGINT NULL,
    ADD COLUMN manual_actual_recipient_name_snapshot TEXT NULL,
    ADD COLUMN manual_actual_current_worker_id BIGINT NULL,
    ADD COLUMN manual_actual_current_manager_id BIGINT NULL,
    ADD COLUMN manual_actual_reason VARCHAR(500) NULL,
    ADD COLUMN manual_actual_receipt_url TEXT NULL,
    ADD COLUMN manual_actual_actor VARCHAR(150) NULL,
    ADD COLUMN manual_actual_recipient_frozen_at DATETIME(6) NULL,
    ADD INDEX idx_payment_links_manual_actual_profile (manual_actual_recipient_profile_id, id);
