CREATE TABLE owner_manual_card_payment_approvals (
    id BIGINT NOT NULL AUTO_INCREMENT,
    payment_link_id BIGINT NOT NULL,
    order_id BIGINT NOT NULL,
    amount_kopecks BIGINT NOT NULL,
    recipient_key VARCHAR(180) NOT NULL,
    recipient_type VARCHAR(24) NOT NULL,
    recipient_profile_id BIGINT NULL,
    reason VARCHAR(500) NOT NULL,
    receipt_url TEXT NULL,
    requested_by VARCHAR(150) NOT NULL,
    callback_token_hash CHAR(64) NOT NULL,
    status VARCHAR(24) NOT NULL,
    requested_at DATETIME(6) NOT NULL,
    attempt_count INT NOT NULL DEFAULT 0,
    last_attempt_at DATETIME(6) NULL,
    last_error VARCHAR(512) NULL,
    approved_by_user_id BIGINT NULL,
    approved_by VARCHAR(150) NULL,
    approved_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_owner_manual_card_approval_link (payment_link_id),
    KEY idx_owner_manual_card_approval_order (order_id),
    KEY idx_owner_manual_card_approval_status (status, requested_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
