INSERT INTO notification_media_rules (event_code,recipient_type,enabled,image_probability_percent,cooldown_minutes,created_at,updated_at)
VALUES
('WORKER_STREAK_15','WORKER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('WORKER_NAGUL_GUIDE','WORKER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('WORKER_FRESH_ACCOUNT_GUIDE','WORKER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('WORKER_TEXT_GUIDE','WORKER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('WORKER_TEXT_PENDING','WORKER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('WORKER_TEXT_SAVED','WORKER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('WORKER_NAGUL_DONE','WORKER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('WORKER_PUBLICATION_DONE','WORKER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('WORKER_THREE_PUBLICATIONS','WORKER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('WORKER_RATING_GUIDE','WORKER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('WORKER_RATING_DONE','WORKER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('WORKER_RECOVERY_GUIDE','WORKER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('WORKER_RECOVERY_FINISH','WORKER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('WORKER_ACCOUNT_CHANGED','WORKER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('WORKER_UNSAVED_CHANGES','WORKER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('WORKER_SITE_ERROR','WORKER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('WORKER_NETWORK_BLOCKED','WORKER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('MANAGER_CLIENT_CHAT_PENDING','MANAGER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('MANAGER_BAD_REVIEW_INVOICED','MANAGER',b'0',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('WORKER_ACCOUNT_LOGIN_GUIDE','WORKER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6)),
('MANAGER_PAYMENT_PENDING','MANAGER',b'1',100,360,CURRENT_TIMESTAMP(6),CURRENT_TIMESTAMP(6))
ON DUPLICATE KEY UPDATE event_code=VALUES(event_code);
