CREATE TABLE IF NOT EXISTS manager_daily_control_concrete_items (
    control_entity_id BIGINT NOT NULL AUTO_INCREMENT,
    control_id BIGINT NOT NULL,
    parent_item_id BIGINT NOT NULL,
    entity_key VARCHAR(180) NOT NULL,
    entity_type VARCHAR(40) NOT NULL,
    entity_id BIGINT NULL,
    title VARCHAR(220) NOT NULL,
    subtitle VARCHAR(500) NULL,
    status_label VARCHAR(120) NULL,
    age_days BIGINT NULL,
    reason VARCHAR(500) NULL,
    target_url VARCHAR(500) NULL,
    item_status VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    action_type VARCHAR(40) NULL,
    comment VARCHAR(1000) NULL,
    resolved_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (control_entity_id),
    UNIQUE KEY uk_manager_control_concrete_key (control_id, parent_item_id, entity_key),
    INDEX idx_manager_control_concrete_parent (parent_item_id, item_status),
    INDEX idx_manager_control_concrete_control (control_id, item_status)
);
