CREATE TABLE IF NOT EXISTS analytics_daily_user
(
    analytics_daily_user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    metric_date             DATE           NOT NULL,
    user_id                 BIGINT         NOT NULL,
    role_name               VARCHAR(64)    NOT NULL,
    manager_id              BIGINT         NULL,
    manager_user_id         BIGINT         NULL,
    salary_sum              DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    salary_entry_count      BIGINT         NOT NULL DEFAULT 0,
    salary_review_count     BIGINT         NOT NULL DEFAULT 0,
    payment_sum             DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    payment_count           BIGINT         NOT NULL DEFAULT 0,
    new_companies_count     BIGINT         NOT NULL DEFAULT 0,
    new_orders_count        BIGINT         NOT NULL DEFAULT 0,
    correction_orders_count BIGINT         NOT NULL DEFAULT 0,
    published_reviews_count BIGINT         NOT NULL DEFAULT 0,
    reviews_to_publish_count BIGINT        NOT NULL DEFAULT 0,
    reviews_to_walk_count   BIGINT         NOT NULL DEFAULT 0,
    leads_new_count         BIGINT         NOT NULL DEFAULT 0,
    leads_in_work_count     BIGINT         NOT NULL DEFAULT 0,
    created_at              DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at              DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT uk_analytics_daily_user_date_user_role UNIQUE (metric_date, user_id, role_name),
    CONSTRAINT fk_analytics_daily_user_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_analytics_daily_user_manager_user FOREIGN KEY (manager_user_id) REFERENCES users (id) ON DELETE SET NULL,
    INDEX idx_analytics_daily_user_date (metric_date),
    INDEX idx_analytics_daily_user_user_date (user_id, metric_date),
    INDEX idx_analytics_daily_user_role_date (role_name, metric_date),
    INDEX idx_analytics_daily_user_manager_date (manager_user_id, metric_date)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS analytics_monthly_user
(
    analytics_monthly_user_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    month_start               DATE           NOT NULL,
    user_id                   BIGINT         NOT NULL,
    role_name                 VARCHAR(64)    NOT NULL,
    manager_id                BIGINT         NULL,
    manager_user_id           BIGINT         NULL,
    period_closed             BIT            NOT NULL DEFAULT 0,
    source_days_count         INT            NOT NULL DEFAULT 0,
    salary_sum                DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    salary_entry_count        BIGINT         NOT NULL DEFAULT 0,
    salary_review_count       BIGINT         NOT NULL DEFAULT 0,
    payment_sum               DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    payment_count             BIGINT         NOT NULL DEFAULT 0,
    new_companies_count       BIGINT         NOT NULL DEFAULT 0,
    new_orders_count          BIGINT         NOT NULL DEFAULT 0,
    correction_orders_count   BIGINT         NOT NULL DEFAULT 0,
    published_reviews_count   BIGINT         NOT NULL DEFAULT 0,
    reviews_to_publish_count  BIGINT         NOT NULL DEFAULT 0,
    reviews_to_walk_count     BIGINT         NOT NULL DEFAULT 0,
    leads_new_count           BIGINT         NOT NULL DEFAULT 0,
    leads_in_work_count       BIGINT         NOT NULL DEFAULT 0,
    last_rebuilt_at           DATETIME(6)    NULL,
    created_at                DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at                DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT uk_analytics_monthly_user_month_user_role UNIQUE (month_start, user_id, role_name),
    CONSTRAINT fk_analytics_monthly_user_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_analytics_monthly_user_manager_user FOREIGN KEY (manager_user_id) REFERENCES users (id) ON DELETE SET NULL,
    INDEX idx_analytics_monthly_user_month (month_start),
    INDEX idx_analytics_monthly_user_user_month (user_id, month_start),
    INDEX idx_analytics_monthly_user_role_month (role_name, month_start),
    INDEX idx_analytics_monthly_user_manager_month (manager_user_id, month_start)
) ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS analytics_monthly_total
(
    analytics_monthly_total_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    month_start                DATE           NOT NULL,
    scope_key                  VARCHAR(96)    NOT NULL,
    scope_type                 VARCHAR(32)    NOT NULL,
    scope_user_id              BIGINT         NULL,
    period_closed              BIT            NOT NULL DEFAULT 0,
    source_user_count          BIGINT         NOT NULL DEFAULT 0,
    source_days_count          INT            NOT NULL DEFAULT 0,
    salary_sum                 DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    salary_entry_count         BIGINT         NOT NULL DEFAULT 0,
    salary_review_count        BIGINT         NOT NULL DEFAULT 0,
    payment_sum                DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    payment_count              BIGINT         NOT NULL DEFAULT 0,
    new_companies_count        BIGINT         NOT NULL DEFAULT 0,
    new_orders_count           BIGINT         NOT NULL DEFAULT 0,
    correction_orders_count    BIGINT         NOT NULL DEFAULT 0,
    published_reviews_count    BIGINT         NOT NULL DEFAULT 0,
    reviews_to_publish_count   BIGINT         NOT NULL DEFAULT 0,
    reviews_to_walk_count      BIGINT         NOT NULL DEFAULT 0,
    leads_new_count            BIGINT         NOT NULL DEFAULT 0,
    leads_in_work_count        BIGINT         NOT NULL DEFAULT 0,
    last_rebuilt_at            DATETIME(6)    NULL,
    created_at                 DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at                 DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT uk_analytics_monthly_total_month_scope UNIQUE (month_start, scope_key),
    CONSTRAINT fk_analytics_monthly_total_scope_user FOREIGN KEY (scope_user_id) REFERENCES users (id) ON DELETE CASCADE,
    INDEX idx_analytics_monthly_total_month (month_start),
    INDEX idx_analytics_monthly_total_scope_month (scope_key, month_start),
    INDEX idx_analytics_monthly_total_scope_user_month (scope_user_id, month_start)
) ENGINE = InnoDB;
