CREATE TABLE IF NOT EXISTS analytics_daily_total
(
    analytics_daily_total_id BIGINT AUTO_INCREMENT PRIMARY KEY,
    metric_date              DATE           NOT NULL,
    scope_key                VARCHAR(96)    NOT NULL,
    scope_type               VARCHAR(32)    NOT NULL,
    scope_user_id            BIGINT         NULL,
    period_closed            BIT            NOT NULL DEFAULT 0,
    source_user_count        BIGINT         NOT NULL DEFAULT 0,
    salary_sum               DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    salary_entry_count       BIGINT         NOT NULL DEFAULT 0,
    salary_review_count      BIGINT         NOT NULL DEFAULT 0,
    payment_sum              DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    payment_count            BIGINT         NOT NULL DEFAULT 0,
    new_companies_count      BIGINT         NOT NULL DEFAULT 0,
    new_orders_count         BIGINT         NOT NULL DEFAULT 0,
    correction_orders_count  BIGINT         NOT NULL DEFAULT 0,
    published_reviews_count  BIGINT         NOT NULL DEFAULT 0,
    reviews_to_publish_count BIGINT         NOT NULL DEFAULT 0,
    reviews_to_walk_count    BIGINT         NOT NULL DEFAULT 0,
    leads_new_count          BIGINT         NOT NULL DEFAULT 0,
    leads_in_work_count      BIGINT         NOT NULL DEFAULT 0,
    last_rebuilt_at          DATETIME(6)    NULL,
    created_at               DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at               DATETIME(6)    NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    CONSTRAINT uk_analytics_daily_total_date_scope UNIQUE (metric_date, scope_key),
    CONSTRAINT fk_analytics_daily_total_scope_user FOREIGN KEY (scope_user_id) REFERENCES users (id) ON DELETE CASCADE,
    INDEX idx_analytics_daily_total_date (metric_date),
    INDEX idx_analytics_daily_total_scope_date (scope_key, metric_date),
    INDEX idx_analytics_daily_total_scope_user_date (scope_user_id, metric_date)
) ENGINE = InnoDB;
