ALTER TABLE leads
    ADD COLUMN company_name VARCHAR(255) NULL,
    ADD COLUMN phones VARCHAR(1000) NULL,
    ADD COLUMN mobile_phones VARCHAR(1000) NULL,
    ADD COLUMN whatsapp_phones VARCHAR(1000) NULL,
    ADD COLUMN emails VARCHAR(1000) NULL,
    ADD COLUMN websites VARCHAR(2000) NULL,
    ADD COLUMN vk_url VARCHAR(1000) NULL,
    ADD COLUMN telegram_url VARCHAR(1000) NULL,
    ADD COLUMN industries VARCHAR(1000) NULL,
    ADD COLUMN company_type VARCHAR(500) NULL,
    ADD COLUMN region VARCHAR(100) NULL,
    ADD COLUMN address VARCHAR(1000) NULL;
