CREATE TABLE payment_links (
    id BIGINT NOT NULL AUTO_INCREMENT,
    token VARCHAR(96) NOT NULL,
    order_id BIGINT NOT NULL,
    amount_kopecks BIGINT NOT NULL,
    description VARCHAR(140) NOT NULL,
    payer_email VARCHAR(320) NULL,
    status VARCHAR(32) NOT NULL,
    tbank_payment_id VARCHAR(64) NULL,
    tbank_order_id VARCHAR(36) NULL,
    tbank_terminal_key VARCHAR(64) NULL,
    payment_url VARCHAR(1024) NULL,
    last_error VARCHAR(512) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    expires_at DATETIME(6) NOT NULL,
    initiated_at DATETIME(6) NULL,
    paid_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_payment_links_token UNIQUE (token),
    CONSTRAINT uk_payment_links_tbank_order_id UNIQUE (tbank_order_id),
    CONSTRAINT fk_payment_links_order FOREIGN KEY (order_id) REFERENCES orders (order_id),
    INDEX idx_payment_links_order (order_id),
    INDEX idx_payment_links_tbank_payment_id (tbank_payment_id)
);
