package com.hunt.otziv.contractor_payments.model;

/** Stable, non-PII reason codes for routing metrics and support diagnostics. */
public enum ContractorRoutingDecisionReason {
    SPECIALIST_SELECTED,
    MANAGER_SELECTED,

    SPECIALIST_NOT_ASSIGNED,
    MANAGER_NOT_ASSIGNED,
    MIXED_SPECIALISTS,
    PRIOR_PAYMENT_EVIDENCE,
    COMPANY_REQUIRES_OWNER_PAYMENT,

    USER_INACTIVE,
    REQUIRED_ROLE_MISSING,
    PROFILE_NOT_FOUND,
    PROFILE_DISABLED,
    LIVE_PROFILE_DISABLED,
    PROFILE_IDENTITY_MISMATCH,
    RECIPIENT_DETAILS_INCOMPLETE,
    INSUFFICIENT_AVAILABLE_BALANCE,

    LIMIT_CONFIGURATION_INVALID,
    LIMIT_ROUTE_INPUT_INVALID,
    LIMIT_SINGLE_INVOICE_EXCEEDED,
    LIMIT_DATABASE_CLOCK_INVALID,
    LIMIT_DAILY_TOTALS_INVALID,
    LIMIT_DAILY_TOTAL_OVERFLOW,
    LIMIT_DAILY_AMOUNT_EXCEEDED,
    LIMIT_DAILY_COUNT_EXCEEDED,

    NO_ELIGIBLE_RECIPIENT,
    SOURCE_SNAPSHOT_NOT_READY,
    LEGACY_UNCLASSIFIED
}
