// Generated by contracts/generate-billing.mjs v1.0.0 from Java records and enums. Do not edit.

export interface CommonBillingCompanyResponseWire {
  companyId: number;
  companyTitle: string;
  enabled: boolean;
}

export interface CommonBillingCompanyResponse {
  companyId: number;
  companyTitle: string;
  enabled: boolean;
}

export interface CommonInvoiceSummaryResponseWire {
  id: number;
  accountId: number;
  accountName: string;
  title: string;
  token: string;
  publicUrl: string;
  status: string;
  totalOrders: number;
  readyOrders: number;
  paidOrders: number;
  amount: number;
  paid: number;
  remaining: number;
  amountKopecks: number;
  paidKopecks: number;
  remainingKopecks: number;
  sentAt: string | null;
  lastReminderAt: string | null;
  nextReminderAt: string | null;
  closedAt: string | null;
  closedBy: string | null;
  closeReason: string | null;
  lastError: string | null;
  paymentSuccessNotificationError: string | null;
  tbankOrderId: string | null;
  tbankPaymentId: string | null;
  tbankPaymentAmountKopecks: number | null;
  tbankTerminalLabel: string | null;
  tbankTerminalKey: string | null;
  paymentRouteType: string | null;
  paymentRouteProvider: string | null;
  paymentRouteProfileName: string | null;
  paymentRouteRecipient: string | null;
  paymentRouteManualTaskId: number | null;
  contractorPaymentRoute: boolean;
  paymentRouteSelectedAt: string | null;
  invoicePurpose: string | null;
  supersedesInvoiceId: number | null;
  invoicePaymentMode: string | null;
  paperInvoiceIssuedAt: string | null;
}

export interface CommonInvoiceSummaryResponse {
  id: number;
  accountId: number;
  accountName: string;
  title: string;
  token: string;
  publicUrl: string;
  status: string;
  totalOrders: number;
  readyOrders: number;
  paidOrders: number;
  amount: number;
  paid: number;
  remaining: number;
  amountKopecks: number;
  paidKopecks: number;
  remainingKopecks: number;
  sentAt?: string | null;
  lastReminderAt?: string | null;
  nextReminderAt?: string | null;
  closedAt?: string | null;
  closedBy?: string | null;
  closeReason?: string | null;
  lastError?: string | null;
  paymentSuccessNotificationError?: string | null;
  tbankOrderId?: string | null;
  tbankPaymentId?: string | null;
  tbankPaymentAmountKopecks?: number | null;
  tbankTerminalLabel?: string | null;
  tbankTerminalKey?: string | null;
  paymentRouteType?: string | null;
  paymentRouteProvider?: string | null;
  paymentRouteProfileName?: string | null;
  paymentRouteRecipient?: string | null;
  paymentRouteManualTaskId?: number | null;
  contractorPaymentRoute: boolean;
  paymentRouteSelectedAt?: string | null;
  invoicePurpose?: string | null;
  supersedesInvoiceId?: number | null;
  invoicePaymentMode?: InvoicePaymentMode | null;
  paperInvoiceIssuedAt?: string | null;
}

export interface CommonBillingAccountResponseWire {
  id: number;
  name: string;
  enabled: boolean;
  autoRepeatOrders: boolean;
  managerId: number | null;
  managerName: string | null;
  invoiceCompanyId: number | null;
  invoiceCompanyTitle: string | null;
  companies: CommonBillingCompanyResponseWire[];
  currentInvoice: CommonInvoiceSummaryResponseWire | null;
  invoicePaymentMode: string | null;
}

export interface CommonBillingAccountResponse {
  id: number;
  name: string;
  enabled: boolean;
  autoRepeatOrders: boolean;
  managerId?: number | null;
  managerName?: string | null;
  invoiceCompanyId?: number | null;
  invoiceCompanyTitle?: string | null;
  companies: CommonBillingCompanyResponse[];
  currentInvoice?: CommonInvoiceSummaryResponse | null;
  invoicePaymentMode?: InvoicePaymentMode | null;
}

export interface PublicPaymentLinkResponseWire {
  token: string;
  orderId: number | null;
  companyTitle: string;
  filialTitle: string;
  serviceTitle: string;
  amount: number;
  amountKopecks: number;
  description: string;
  payerEmail: string | null;
  status: string;
  paymentMethod: string;
  provider: string | null;
  expiresAt: string | null;
  payable: boolean;
  paymentPageMode: string;
  sbpBankSelectionSupported: boolean | null;
  tpayEnabled: boolean;
  sberpayEnabled: boolean;
  mirpayEnabled: boolean;
  manualPaymentType: string | null;
  manualPhone: string | null;
  manualRecipientName: string | null;
  manualBankName: string | null;
  manualPaymentUrl: string | null;
  manualPaymentButtonLabel: string | null;
  manualComment: string | null;
  receiptStatus: string | null;
}

export interface PublicPaymentLinkResponse {
  token: string;
  orderId?: number | null;
  companyTitle: string;
  filialTitle: string;
  serviceTitle: string;
  amount: number;
  amountKopecks: number;
  description: string;
  payerEmail?: string | null;
  status: string;
  paymentMethod?: string;
  provider?: string | null;
  expiresAt: string | null;
  payable: boolean;
  paymentPageMode?: string;
  sbpBankSelectionSupported?: boolean | null;
  tpayEnabled?: boolean;
  sberpayEnabled?: boolean;
  mirpayEnabled?: boolean;
  manualPaymentType?: string | null;
  manualPhone?: string | null;
  manualRecipientName?: string | null;
  manualBankName?: string | null;
  manualPaymentUrl?: string | null;
  manualPaymentButtonLabel?: string | null;
  manualComment?: string | null;
  receiptStatus?: string | null;
}

export interface DeliveryOperationWire {
  operationId: string;
  status: string;
  attempts: number;
  errorCode: string | null;
}

export interface DeliveryOperation {
  operationId: string;
  status: string;
  attempts: number;
  errorCode: string | null;
}

export const BILLING_PAYMENT_CONTRACT_VERSION = '1.1.0';
export const billingPaymentEnums = {
  "CommonInvoiceStatus": [
    "COLLECTING",
    "READY",
    "INVOICED",
    "REMINDER",
    "PARTIALLY_PAID",
    "NEEDS_ATTENTION",
    "PAID",
    "UNPAID",
    "BAN",
    "ARCHIVED",
    "DISABLED"
  ],
  "InvoicePaymentMode": [
    "AUTO_ROUTING",
    "EMPLOYEE_REQUISITES",
    "OWNER_TBANK",
    "OWNER_PAPER_INVOICE"
  ],
  "PaymentLinkStatus": [
    "CREATED",
    "INITIATED",
    "AUTHORIZED",
    "WAITING_MANUAL_PAYMENT",
    "MANUAL_REPORTED",
    "TEST_CONFIRMED",
    "CONFIRMED",
    "AMOUNT_MISMATCH",
    "REJECTED",
    "CANCELED",
    "REVERSED",
    "PARTIAL_REVERSED",
    "REFUNDED",
    "PARTIAL_REFUNDED",
    "EXPIRED",
    "NEEDS_RECONCILIATION",
    "FAILED"
  ],
  "PaymentMethod": [
    "BANK_FORM",
    "SBP_QR",
    "MANUAL_MOBILE_BANK",
    "MANUAL_EXTERNAL_LINK",
    "OWNER_PAPER_INVOICE"
  ],
  "TbankPaymentPageMode": [
    "SBP_PRIMARY",
    "BANK_PRIMARY",
    "SBP_PAY_ONLY",
    "SBP_ONLY",
    "BANK_ONLY"
  ]
} as const;
export type InvoicePaymentMode = typeof billingPaymentEnums.InvoicePaymentMode[number];
export const billingPaymentSchemas = {
  "CommonBillingCompanyResponse": {
    "type": "object",
    "additionalProperties": true,
    "required": [
      "companyId",
      "companyTitle",
      "enabled"
    ],
    "properties": {
      "companyId": {
        "type": "integer"
      },
      "companyTitle": {
        "type": "string"
      },
      "enabled": {
        "type": "boolean"
      }
    }
  },
  "CommonInvoiceSummaryResponse": {
    "type": "object",
    "additionalProperties": true,
    "required": [
      "id",
      "accountId",
      "accountName",
      "title",
      "token",
      "publicUrl",
      "status",
      "totalOrders",
      "readyOrders",
      "paidOrders",
      "amount",
      "paid",
      "remaining",
      "amountKopecks",
      "paidKopecks",
      "remainingKopecks",
      "sentAt",
      "lastReminderAt",
      "nextReminderAt",
      "closedAt",
      "closedBy",
      "closeReason",
      "lastError",
      "paymentSuccessNotificationError",
      "tbankOrderId",
      "tbankPaymentId",
      "tbankPaymentAmountKopecks",
      "tbankTerminalLabel",
      "tbankTerminalKey",
      "paymentRouteType",
      "paymentRouteProvider",
      "paymentRouteProfileName",
      "paymentRouteRecipient",
      "paymentRouteManualTaskId",
      "contractorPaymentRoute",
      "paymentRouteSelectedAt",
      "invoicePurpose",
      "supersedesInvoiceId",
      "invoicePaymentMode",
      "paperInvoiceIssuedAt"
    ],
    "properties": {
      "id": {
        "type": "integer"
      },
      "accountId": {
        "type": "integer"
      },
      "accountName": {
        "type": "string"
      },
      "title": {
        "type": "string"
      },
      "token": {
        "type": "string"
      },
      "publicUrl": {
        "type": "string"
      },
      "status": {
        "type": "string"
      },
      "totalOrders": {
        "type": "integer"
      },
      "readyOrders": {
        "type": "integer"
      },
      "paidOrders": {
        "type": "integer"
      },
      "amount": {
        "type": "number"
      },
      "paid": {
        "type": "number"
      },
      "remaining": {
        "type": "number"
      },
      "amountKopecks": {
        "type": "integer"
      },
      "paidKopecks": {
        "type": "integer"
      },
      "remainingKopecks": {
        "type": "integer"
      },
      "sentAt": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "lastReminderAt": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "nextReminderAt": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "closedAt": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "closedBy": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "closeReason": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "lastError": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "paymentSuccessNotificationError": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "tbankOrderId": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "tbankPaymentId": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "tbankPaymentAmountKopecks": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ]
      },
      "tbankTerminalLabel": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "tbankTerminalKey": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "paymentRouteType": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "paymentRouteProvider": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "paymentRouteProfileName": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "paymentRouteRecipient": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "paymentRouteManualTaskId": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ]
      },
      "contractorPaymentRoute": {
        "type": "boolean"
      },
      "paymentRouteSelectedAt": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "invoicePurpose": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "supersedesInvoiceId": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ]
      },
      "invoicePaymentMode": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "paperInvoiceIssuedAt": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      }
    }
  },
  "CommonBillingAccountResponse": {
    "type": "object",
    "additionalProperties": true,
    "required": [
      "id",
      "name",
      "enabled",
      "autoRepeatOrders",
      "managerId",
      "managerName",
      "invoiceCompanyId",
      "invoiceCompanyTitle",
      "companies",
      "currentInvoice",
      "invoicePaymentMode"
    ],
    "properties": {
      "id": {
        "type": "integer"
      },
      "name": {
        "type": "string"
      },
      "enabled": {
        "type": "boolean"
      },
      "autoRepeatOrders": {
        "type": "boolean"
      },
      "managerId": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ]
      },
      "managerName": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "invoiceCompanyId": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ]
      },
      "invoiceCompanyTitle": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "companies": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/CommonBillingCompanyResponse"
        }
      },
      "currentInvoice": {
        "anyOf": [
          {
            "$ref": "#/components/schemas/CommonInvoiceSummaryResponse"
          },
          {
            "type": "null"
          }
        ]
      },
      "invoicePaymentMode": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      }
    }
  },
  "PublicPaymentLinkResponse": {
    "type": "object",
    "additionalProperties": true,
    "required": [
      "token",
      "orderId",
      "companyTitle",
      "filialTitle",
      "serviceTitle",
      "amount",
      "amountKopecks",
      "description",
      "payerEmail",
      "status",
      "paymentMethod",
      "provider",
      "expiresAt",
      "payable",
      "paymentPageMode",
      "sbpBankSelectionSupported",
      "tpayEnabled",
      "sberpayEnabled",
      "mirpayEnabled",
      "manualPaymentType",
      "manualPhone",
      "manualRecipientName",
      "manualBankName",
      "manualPaymentUrl",
      "manualPaymentButtonLabel",
      "manualComment",
      "receiptStatus"
    ],
    "properties": {
      "token": {
        "type": "string"
      },
      "orderId": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ]
      },
      "companyTitle": {
        "type": "string"
      },
      "filialTitle": {
        "type": "string"
      },
      "serviceTitle": {
        "type": "string"
      },
      "amount": {
        "type": "number"
      },
      "amountKopecks": {
        "type": "integer"
      },
      "description": {
        "type": "string"
      },
      "payerEmail": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "status": {
        "type": "string"
      },
      "paymentMethod": {
        "type": "string"
      },
      "provider": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "expiresAt": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "payable": {
        "type": "boolean"
      },
      "paymentPageMode": {
        "type": "string"
      },
      "sbpBankSelectionSupported": {
        "anyOf": [
          {
            "type": "boolean"
          },
          {
            "type": "null"
          }
        ]
      },
      "tpayEnabled": {
        "type": "boolean"
      },
      "sberpayEnabled": {
        "type": "boolean"
      },
      "mirpayEnabled": {
        "type": "boolean"
      },
      "manualPaymentType": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "manualPhone": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "manualRecipientName": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "manualBankName": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "manualPaymentUrl": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "manualPaymentButtonLabel": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "manualComment": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      },
      "receiptStatus": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      }
    }
  },
  "DeliveryOperation": {
    "type": "object",
    "additionalProperties": true,
    "required": [
      "operationId",
      "status",
      "attempts",
      "errorCode"
    ],
    "properties": {
      "operationId": {
        "type": "string"
      },
      "status": {
        "type": "string"
      },
      "attempts": {
        "type": "integer",
        "minimum": 0
      },
      "errorCode": {
        "anyOf": [
          {
            "type": "string"
          },
          {
            "type": "null"
          }
        ]
      }
    }
  }
} as const;
export const billingPaymentOptionalFields: Record<string, readonly string[]> = {
  "CommonBillingCompanyResponse": [],
  "CommonInvoiceSummaryResponse": [
    "sentAt",
    "lastReminderAt",
    "nextReminderAt",
    "closedAt",
    "closedBy",
    "closeReason",
    "lastError",
    "paymentSuccessNotificationError",
    "tbankOrderId",
    "tbankPaymentId",
    "tbankPaymentAmountKopecks",
    "tbankTerminalLabel",
    "tbankTerminalKey",
    "paymentRouteType",
    "paymentRouteProfileName",
    "paymentRouteProvider",
    "paymentRouteRecipient",
    "paymentRouteManualTaskId",
    "paymentRouteSelectedAt",
    "invoicePurpose",
    "supersedesInvoiceId",
    "invoicePaymentMode",
    "paperInvoiceIssuedAt"
  ],
  "CommonBillingAccountResponse": [
    "managerId",
    "managerName",
    "invoiceCompanyId",
    "invoiceCompanyTitle",
    "currentInvoice",
    "invoicePaymentMode"
  ],
  "PublicPaymentLinkResponse": [
    "provider",
    "sbpBankSelectionSupported",
    "orderId",
    "payerEmail",
    "paymentMethod",
    "paymentPageMode",
    "tpayEnabled",
    "sberpayEnabled",
    "mirpayEnabled",
    "manualPaymentType",
    "manualPhone",
    "manualRecipientName",
    "manualBankName",
    "manualPaymentUrl",
    "manualPaymentButtonLabel",
    "manualComment",
    "receiptStatus"
  ],
  "DeliveryOperation": []
};
