// Generated by contracts/generate.mjs v1.0.0 from Java records. Do not edit.

export interface OptionResponse {
  id: number;
  label: string;
}

export interface OrderEditResponse {
  id: number;
  companyId: number | null;
  companyTitle: string;
  status: string;
  sum: number | null;
  amount: number | null;
  counter: number | null;
  created: string;
  changed: string;
  payDay: string;
  orderComments: string;
  commentsCompany: string;
  complete: boolean;
  filial: OptionResponse | null;
  manager: OptionResponse | null;
  worker: OptionResponse | null;
  filials: OptionResponse[];
  managers: OptionResponse[];
  workers: OptionResponse[];
  canComplete: boolean;
  canDelete: boolean;
  canCancelPayment: boolean;
}

/** Compatible view of the wire response; omitted capabilities confer no permission. */
export interface OrderEditPayload {
  id: number;
  companyId: number | null;
  companyTitle: string;
  status: string;
  sum?: number;
  amount?: number;
  counter?: number;
  created: string;
  changed: string;
  payDay: string;
  orderComments: string;
  commentsCompany: string;
  complete: boolean;
  filial?: OptionResponse | null;
  manager?: OptionResponse | null;
  worker?: OptionResponse | null;
  filials: OptionResponse[];
  managers: OptionResponse[];
  workers: OptionResponse[];
  canComplete: boolean;
  canDelete: boolean;
  canCancelPayment?: boolean;
}

export const ORDER_EDITOR_CONTRACT_VERSION = '1.1.0';
export const orderEditorSchemas = {
  "OptionResponse": {
    "type": "object",
    "additionalProperties": true,
    "required": [
      "id",
      "label"
    ],
    "properties": {
      "id": {
        "type": "integer"
      },
      "label": {
        "type": "string"
      }
    }
  },
  "OrderEditResponse": {
    "type": "object",
    "additionalProperties": true,
    "required": [
      "id",
      "companyId",
      "companyTitle",
      "status",
      "sum",
      "amount",
      "counter",
      "created",
      "changed",
      "payDay",
      "orderComments",
      "commentsCompany",
      "complete",
      "filial",
      "manager",
      "worker",
      "filials",
      "managers",
      "workers",
      "canComplete",
      "canDelete",
      "canCancelPayment"
    ],
    "properties": {
      "id": {
        "type": "integer"
      },
      "companyId": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ]
      },
      "companyTitle": {
        "type": "string"
      },
      "status": {
        "type": "string"
      },
      "sum": {
        "anyOf": [
          {
            "type": "number"
          },
          {
            "type": "null"
          }
        ]
      },
      "amount": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ]
      },
      "counter": {
        "anyOf": [
          {
            "type": "integer"
          },
          {
            "type": "null"
          }
        ]
      },
      "created": {
        "type": "string"
      },
      "changed": {
        "type": "string"
      },
      "payDay": {
        "type": "string"
      },
      "orderComments": {
        "type": "string"
      },
      "commentsCompany": {
        "type": "string"
      },
      "complete": {
        "type": "boolean"
      },
      "filial": {
        "anyOf": [
          {
            "$ref": "#/components/schemas/OptionResponse"
          },
          {
            "type": "null"
          }
        ]
      },
      "manager": {
        "anyOf": [
          {
            "$ref": "#/components/schemas/OptionResponse"
          },
          {
            "type": "null"
          }
        ]
      },
      "worker": {
        "anyOf": [
          {
            "$ref": "#/components/schemas/OptionResponse"
          },
          {
            "type": "null"
          }
        ]
      },
      "filials": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/OptionResponse"
        }
      },
      "managers": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/OptionResponse"
        }
      },
      "workers": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/OptionResponse"
        }
      },
      "canComplete": {
        "type": "boolean"
      },
      "canDelete": {
        "type": "boolean"
      },
      "canCancelPayment": {
        "type": "boolean"
      }
    }
  }
} as const;
export const orderEditorOptionalFields: Record<string, readonly string[]> = {
  "OrderEditResponse": [
    "sum",
    "amount",
    "counter",
    "filial",
    "manager",
    "worker",
    "canCancelPayment"
  ]
};
export const normalizedOrderEditorNumbers = ["sum","amount","counter"] as const;
export const managerOrderEditPath = (orderId: number): string => {
  if (!Number.isSafeInteger(orderId) || orderId <= 0) throw new Error('Invalid order ID');
  return `/api/manager/orders/${orderId}/edit`;
};
