import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
const config = JSON.parse(fs.readFileSync(new URL('billing-payments.config.json', import.meta.url), 'utf8'));
const records = new Map();
for (const [name, relative] of Object.entries(config.records)) {
  const source = fs.readFileSync(path.join(root, relative), 'utf8');
  const match = source.match(new RegExp(`public\\s+record\\s+${name}\\s*\\(([\\s\\S]*?)\\)\\s*\\{`));
  if (!match) throw new Error(`Unsupported Java record ${name}`);
  records.set(name, match[1].split(',').map(part => {
    const field = part.trim().match(/^(List<\w+>|\w+)\s+(\w+)$/);
    if (!field) throw new Error(`Unsupported Java component ${name}.${part}`);
    return { type: field[1], name: field[2] };
  }));
  for (const option of ['nullable', 'optionalForCompatibility', 'nonNegative']) {
    for (const field of config[option][name] ?? []) {
      if (!records.get(name).some(item => item.name === field)) throw new Error(`Unknown ${option} field ${name}.${field}`);
    }
  }
}
const enums = Object.fromEntries(Object.entries(config.enums).map(([name, relative]) => {
  const source = fs.readFileSync(path.join(root, relative), 'utf8').replace(/\/\*[\s\S]*?\*\/|\/\/[^\n]*/g, '');
  const match = source.match(new RegExp(`public\\s+enum\\s+${name}\\s*\\{([^;}]+)`));
  if (!match) throw new Error(`Unsupported Java enum ${name}`);
  const values = match[1].split(',').map(value => value.trim());
  if (values.some(value => !/^[A-Z][A-Z0-9_]*$/.test(value))) throw new Error(`Unsupported Java enum value ${name}`);
  return [name, values];
}));
const scalars = { String: 'string', LocalDateTime: 'string', boolean: 'boolean', Boolean: 'boolean', Long: 'integer', Integer: 'integer', long: 'integer', int: 'integer', BigDecimal: 'number' };
function schema(type) {
  if (type.startsWith('List<')) return { type: 'array', items: schema(type.slice(5, -1)) };
  if (records.has(type)) return { $ref: `#/components/schemas/${type}` };
  if (!scalars[type]) throw new Error(`Unsupported Java type ${type}`);
  return { type: scalars[type] };
}
function tsType(type, wire = false) {
  if (type.startsWith('List<')) return `${tsType(type.slice(5, -1), wire)}[]`;
  if (records.has(type)) return `${type}${wire ? 'Wire' : ''}`;
  if (!scalars[type]) throw new Error(`Unsupported TypeScript type ${type}`);
  return scalars[type] === 'integer' ? 'number' : scalars[type];
}
const schemas = Object.fromEntries([...records].map(([name, fields]) => [name, {
  type: 'object', additionalProperties: true, required: fields.map(field => field.name),
  properties: Object.fromEntries(fields.map(field => {
    const property = { ...schema(field.type), ...((config.nonNegative[name] ?? []).includes(field.name) ? { minimum: 0 } : {}) };
    return [field.name, (config.nullable[name] ?? []).includes(field.name) ? { anyOf: [property, { type: 'null' }] } : property];
  }))
}]));
const paths = {};
for (const operation of config.operations) {
  const controller = fs.readFileSync(path.join(root, operation.controller), 'utf8');
  if (!controller.includes(`@GetMapping("${operation.path}")`) || !controller.includes(operation.response)) {
    throw new Error(`Controller contract drift ${operation.path}`);
  }
  const response = { $ref: `#/components/schemas/${operation.response}` };
  const parameters = [...operation.path.matchAll(/\{(\w+)\}/g)].map(match => ({ name: match[1], in: 'path', required: true, schema: { type: match[1] === 'token' ? 'string' : 'integer' } }));
  paths[operation.path] = { get: { parameters, responses: { 200: { description: operation.response, content: { 'application/json': { schema: operation.array ? { type: 'array', items: response } : response } } } } } };
}
const document = { openapi: '3.1.0', info: { title: 'Otziv billing and public payment reads', version: config.version }, 'x-generator-version': config.generatorVersion, paths, components: { schemas }, 'x-known-enum-values': enums, 'x-compatibility-optional-fields': config.optionalForCompatibility };
const declarations = [...records].flatMap(([name, fields]) => [true, false].map(wire => {
  const properties = fields.map(field => {
    const optional = !wire && (config.optionalForCompatibility[name] ?? []).includes(field.name);
    const valueType = !wire && field.name === 'invoicePaymentMode' ? 'InvoicePaymentMode' : tsType(field.type, wire);
    return `  ${field.name}${optional ? '?' : ''}: ${valueType}${(config.nullable[name] ?? []).includes(field.name) ? ' | null' : ''};`;
  });
  return `export interface ${name}${wire ? 'Wire' : ''} {\n${properties.join('\n')}\n}`;
})).join('\n\n');
const generated = `// Generated by contracts/generate-billing.mjs v${config.generatorVersion} from Java records and enums. Do not edit.\n\n${declarations}\n\nexport const BILLING_PAYMENT_CONTRACT_VERSION = '${config.version}';\nexport const billingPaymentEnums = ${JSON.stringify(enums, null, 2)} as const;\nexport type InvoicePaymentMode = typeof billingPaymentEnums.InvoicePaymentMode[number];\nexport const billingPaymentSchemas = ${JSON.stringify(schemas, null, 2)} as const;\nexport const billingPaymentOptionalFields: Record<string, readonly string[]> = ${JSON.stringify(config.optionalForCompatibility, null, 2)};\n`;
for (const [relative, content] of [
  ['contracts/generated/billing-payments.openapi.json', `${JSON.stringify(document, null, 2)}\n`],
  ['shared/client-common/src/billing-payments.generated.ts', generated]
]) {
  const file = path.join(root, relative);
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== content) throw new Error(`Contract drift: run node contracts/generate.mjs (${relative})`);
  } else {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
  }
}
if (JSON.parse(fs.readFileSync(path.join(root, 'shared/client-common/package.json'), 'utf8')).version !== config.version) throw new Error('Billing contract/package version mismatch');
console.log(`Billing/payment contract ${config.version}: ${records.size} Java records, ${Object.keys(enums).length} Java enums checked.`);
