import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

// Deliberately limited record generator: unsupported syntax/types fail the check instead
// of silently emitting an inaccurate DTO. Java remains the source of field names/types.
const root = fileURLToPath(new URL('../', import.meta.url));
const config = JSON.parse(fs.readFileSync(new URL('order-editor.config.json', import.meta.url), 'utf8'));
const records = new Map();
for (const name of config.records) {
  const source = fs.readFileSync(path.join(root, config.dtoDirectory, `${name}.java`), 'utf8');
  const match = source.match(new RegExp(`public\\s+record\\s+${name}\\s*\\(([\\s\\S]*?)\\)\\s*\\{`));
  if (!match) throw new Error(`Unsupported Java record: ${name}`);
  const fields = match[1].split(',').map(part => {
    const field = part.trim().match(/^(List<\w+>|\w+)\s+(\w+)$/);
    if (!field) throw new Error(`Unsupported record component: ${name}.${part}`);
    return { type: field[1], name: field[2] };
  });
  records.set(name, fields);
  for (const option of ['nullable', 'optionalForCompatibility']) {
    for (const field of config[option][name] ?? []) {
      if (!fields.some(item => item.name === field)) throw new Error(`Unknown ${option} field ${name}.${field}`);
    }
  }
}
const controller = fs.readFileSync(path.join(root, config.controller), 'utf8');
if (!controller.includes('@GetMapping("/orders/{orderId}/edit")') || !controller.includes('OrderEditResponse')) {
  throw new Error('Order editor controller mapping changed: review the contract operation');
}
function baseSchema(type) {
  if (type.startsWith('List<')) return { type: 'array', items: baseSchema(type.slice(5, -1)) };
  if (records.has(type)) return { $ref: `#/components/schemas/${type}` };
  if (type === 'String') return { type: 'string' };
  if (type === 'boolean') return { type: 'boolean' };
  if (type === 'Long' || type === 'Integer') return { type: 'integer' };
  if (type === 'BigDecimal') return { type: 'number' };
  throw new Error(`Unsupported Java type: ${type}`);
}
const schemas = Object.fromEntries([...records].map(([name, fields]) => [name, {
  type: 'object', additionalProperties: true,
  required: fields.map(field => field.name),
  properties: Object.fromEntries(fields.map(field => [field.name,
    (config.nullable[name] ?? []).includes(field.name)
      ? { anyOf: [baseSchema(field.type), { type: 'null' }] } : baseSchema(field.type)]))
}]));
const openapi = {
  openapi: '3.1.0', info: { title: 'Otziv order editor read contract', version: config.version },
  'x-generator-version': config.generatorVersion,
  paths: { [config.operation.path]: { get: {
    operationId: 'getManagerOrderEdit',
    parameters: [{ name: 'orderId', in: 'path', required: true, schema: { type: 'integer' } }],
    responses: { 200: { description: 'Order editor', content: { 'application/json': { schema: { $ref: '#/components/schemas/OrderEditResponse' } } } } }
  } } },
  components: { schemas },
  'x-compatibility-optional-fields': config.optionalForCompatibility
};
function typeScript(type) {
  if (type.startsWith('List<')) return `${typeScript(type.slice(5, -1))}[]`;
  if (records.has(type)) return type;
  return { String: 'string', boolean: 'boolean', Long: 'number', Integer: 'number', BigDecimal: 'number' }[type]
    ?? (() => { throw new Error(`Unsupported TypeScript mapping: ${type}`); })();
}
const declarations = [...records].map(([name, fields]) => `export interface ${name} {\n${fields.map(field =>
  `  ${field.name}: ${typeScript(field.type)}${(config.nullable[name] ?? []).includes(field.name) ? ' | null' : ''};`).join('\n')}\n}`).join('\n\n');
const optional = config.optionalForCompatibility.OrderEditResponse;
const normalized = config.normalizeNullToUndefined;
const payload = records.get('OrderEditResponse').map(field =>
  `  ${field.name}${optional.includes(field.name) ? '?' : ''}: ${typeScript(field.type)}${(config.nullable.OrderEditResponse.includes(field.name) && !normalized.includes(field.name)) ? ' | null' : ''};`).join('\n');
const generated = `// Generated by contracts/generate.mjs v${config.generatorVersion} from Java records. Do not edit.\n\n${declarations}\n\n/** Compatible view of the wire response; omitted capabilities confer no permission. */\nexport interface OrderEditPayload {\n${payload}\n}\n\nexport const ORDER_EDITOR_CONTRACT_VERSION = '${config.version}';\nexport const orderEditorSchemas = ${JSON.stringify(schemas, null, 2)} as const;\nexport const orderEditorOptionalFields: Record<string, readonly string[]> = ${JSON.stringify(config.optionalForCompatibility, null, 2)};\nexport const normalizedOrderEditorNumbers = ${JSON.stringify(normalized)} as const;\nexport const managerOrderEditPath = (orderId: number): string => {\n  if (!Number.isSafeInteger(orderId) || orderId <= 0) throw new Error('Invalid order ID');\n  return \`${config.operation.path.replace('{orderId}', '${orderId}')}\`;\n};\n`;
const outputs = new Map([
  ['contracts/generated/order-editor.openapi.json', `${JSON.stringify(openapi, null, 2)}\n`],
  ['shared/client-common/src/order-editor.generated.ts', generated]
]);
const checking = process.argv.includes('--check');
for (const [relative, content] of outputs) {
  const file = path.join(root, relative);
  if (checking) {
    if (!fs.existsSync(file) || fs.readFileSync(file, 'utf8') !== content) throw new Error(`Contract drift: run node contracts/generate.mjs (${relative})`);
  } else {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
  }
}
const packageVersion = JSON.parse(fs.readFileSync(path.join(root, 'shared/client-common/package.json'), 'utf8')).version;
if (packageVersion !== config.version) throw new Error('Package and contract versions differ');
console.log(`${checking ? 'Checked' : 'Generated'} order editor contract ${config.version} from ${records.size} Java records.`);
await import('./generate-billing.mjs');

await import('./generate-client-api.mjs');
