package com.hunt.otziv.worker_performance.dto;

import java.time.LocalDate;
import java.time.LocalDateTime;

public record DailyWorkProgressResponse(
        boolean visible,
        String roleType,
        LocalDate date,
        long completed,
        long active,
        long total,
        int percent,
        boolean checked,
        LocalDateTime firstCompletedAt,
        LocalDateTime lastCompletedAt,
        long averageCloseSeconds,
        long medianCloseSeconds,
        long p90CloseSeconds,
        LocalDateTime firstActivityAt,
        LocalDateTime lastActivityAt,
        long activeWorkSeconds,
        long workWindowSeconds,
        long activityEvents,
        long loadScore,
        int efficiencyScore,
        long openedCount,
        long orderCompletedCount,
        long nagulCompletedCount,
        long publishCompletedCount,
        long badCompletedCount,
        long recoveryCompletedCount,
        long recoveryCreatedCount,
        long orderOverdueCount,
        long totalOverdueCount,
        int speedScore,
        int disciplineScore,
        int workloadScore,
        long botChangeCount,
        long botBlockCount,
        boolean reached100,
        LocalDateTime firstReached100At,
        LocalDateTime lastReached100At,
        String periodType,
        int workingDays,
        int checkedDays,
        int reached100Days,
        boolean closedPeriod,
        boolean updating
) {
    public DailyWorkProgressResponse(
            boolean visible,
            String roleType,
            LocalDate date,
            long completed,
            long active,
            long total,
            int percent,
            boolean checked,
            LocalDateTime firstCompletedAt,
            LocalDateTime lastCompletedAt,
            long averageCloseSeconds,
            long medianCloseSeconds,
            long p90CloseSeconds,
            LocalDateTime firstActivityAt,
            LocalDateTime lastActivityAt,
            long activeWorkSeconds,
            long workWindowSeconds,
            long activityEvents,
            long loadScore,
            int efficiencyScore,
            long openedCount,
            long orderCompletedCount,
            long nagulCompletedCount,
            long publishCompletedCount,
            long badCompletedCount,
            long recoveryCompletedCount,
            long recoveryCreatedCount,
            long orderOverdueCount,
            long totalOverdueCount,
            int speedScore,
            int disciplineScore,
            int workloadScore,
            long botChangeCount,
            long botBlockCount,
            boolean reached100,
            LocalDateTime firstReached100At,
            LocalDateTime lastReached100At,
            String periodType,
            int workingDays,
            int checkedDays,
            int reached100Days,
            boolean closedPeriod
    ) {
        this(
                visible,
                roleType,
                date,
                completed,
                active,
                total,
                percent,
                checked,
                firstCompletedAt,
                lastCompletedAt,
                averageCloseSeconds,
                medianCloseSeconds,
                p90CloseSeconds,
                firstActivityAt,
                lastActivityAt,
                activeWorkSeconds,
                workWindowSeconds,
                activityEvents,
                loadScore,
                efficiencyScore,
                openedCount,
                orderCompletedCount,
                nagulCompletedCount,
                publishCompletedCount,
                badCompletedCount,
                recoveryCompletedCount,
                recoveryCreatedCount,
                orderOverdueCount,
                totalOverdueCount,
                speedScore,
                disciplineScore,
                workloadScore,
                botChangeCount,
                botBlockCount,
                reached100,
                firstReached100At,
                lastReached100At,
                periodType,
                workingDays,
                checkedDays,
                reached100Days,
                closedPeriod,
                false
        );
    }

    public DailyWorkProgressResponse(
            boolean visible,
            String roleType,
            LocalDate date,
            long completed,
            long active,
            long total,
            int percent,
            boolean checked,
            LocalDateTime firstCompletedAt,
            LocalDateTime lastCompletedAt,
            long averageCloseSeconds,
            long medianCloseSeconds,
            long p90CloseSeconds,
            LocalDateTime firstActivityAt,
            LocalDateTime lastActivityAt,
            long activeWorkSeconds,
            long workWindowSeconds,
            long activityEvents,
            long loadScore,
            int efficiencyScore
    ) {
        this(
                visible,
                roleType,
                date,
                completed,
                active,
                total,
                percent,
                checked,
                firstCompletedAt,
                lastCompletedAt,
                averageCloseSeconds,
                medianCloseSeconds,
                p90CloseSeconds,
                firstActivityAt,
                lastActivityAt,
                activeWorkSeconds,
                workWindowSeconds,
                activityEvents,
                loadScore,
                efficiencyScore,
                total,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                false,
                null,
                null,
                "DAY",
                0,
                0,
                0,
                false
        );
    }

    public static DailyWorkProgressResponse hidden(String roleType, LocalDate date) {
        return new DailyWorkProgressResponse(
                false,
                roleType,
                date,
                0,
                0,
                0,
                0,
                false,
                null,
                null,
                0,
                0,
                0,
                null,
                null,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                false,
                null,
                null,
                "DAY",
                0,
                0,
                0,
                false
        );
    }

    public DailyWorkProgressResponse withActiveWorkSeconds(long value) {
        return new DailyWorkProgressResponse(
                visible,
                roleType,
                date,
                completed,
                active,
                total,
                percent,
                checked,
                firstCompletedAt,
                lastCompletedAt,
                averageCloseSeconds,
                medianCloseSeconds,
                p90CloseSeconds,
                firstActivityAt,
                lastActivityAt,
                Math.max(0, value),
                workWindowSeconds,
                activityEvents,
                loadScore,
                efficiencyScore,
                openedCount,
                orderCompletedCount,
                nagulCompletedCount,
                publishCompletedCount,
                badCompletedCount,
                recoveryCompletedCount,
                recoveryCreatedCount,
                orderOverdueCount,
                totalOverdueCount,
                speedScore,
                disciplineScore,
                workloadScore,
                botChangeCount,
                botBlockCount,
                reached100,
                firstReached100At,
                lastReached100At,
                periodType,
                workingDays,
                checkedDays,
                reached100Days,
                closedPeriod,
                updating
        );
    }

    public DailyWorkProgressResponse withWorkloadProgress(
            long completedValue,
            long eligibleValue,
            int percentValue,
            boolean reached100Value,
            LocalDateTime firstReached100AtValue,
            LocalDateTime lastReached100AtValue
    ) {
        long safeCompleted = Math.max(0, completedValue);
        long safeEligible = Math.max(safeCompleted, eligibleValue);
        boolean workloadChecked = safeEligible == 0 || safeCompleted >= safeEligible;
        return new DailyWorkProgressResponse(
                visible,
                roleType,
                date,
                safeCompleted,
                safeEligible - safeCompleted,
                safeEligible,
                Math.max(0, Math.min(100, percentValue)),
                workloadChecked,
                firstCompletedAt,
                lastCompletedAt,
                averageCloseSeconds,
                medianCloseSeconds,
                p90CloseSeconds,
                firstActivityAt,
                lastActivityAt,
                activeWorkSeconds,
                workWindowSeconds,
                activityEvents,
                loadScore,
                efficiencyScore,
                openedCount,
                orderCompletedCount,
                nagulCompletedCount,
                publishCompletedCount,
                badCompletedCount,
                recoveryCompletedCount,
                recoveryCreatedCount,
                orderOverdueCount,
                totalOverdueCount,
                speedScore,
                disciplineScore,
                workloadScore,
                botChangeCount,
                botBlockCount,
                reached100Value,
                reached100Value ? firstReached100AtValue : null,
                reached100Value ? lastReached100AtValue : null,
                periodType,
                workingDays,
                checkedDays,
                reached100Days,
                closedPeriod,
                updating
        );
    }

    public DailyWorkProgressResponse withUpdating(boolean value) {
        if (updating == value) {
            return this;
        }
        return new DailyWorkProgressResponse(
                visible,
                roleType,
                date,
                completed,
                active,
                total,
                percent,
                checked,
                firstCompletedAt,
                lastCompletedAt,
                averageCloseSeconds,
                medianCloseSeconds,
                p90CloseSeconds,
                firstActivityAt,
                lastActivityAt,
                activeWorkSeconds,
                workWindowSeconds,
                activityEvents,
                loadScore,
                efficiencyScore,
                openedCount,
                orderCompletedCount,
                nagulCompletedCount,
                publishCompletedCount,
                badCompletedCount,
                recoveryCompletedCount,
                recoveryCreatedCount,
                orderOverdueCount,
                totalOverdueCount,
                speedScore,
                disciplineScore,
                workloadScore,
                botChangeCount,
                botBlockCount,
                reached100,
                firstReached100At,
                lastReached100At,
                periodType,
                workingDays,
                checkedDays,
                reached100Days,
                closedPeriod,
                value
        );
    }

}
