package com.hunt.otziv.worker_performance.dto;

import java.time.LocalDate;
import java.time.LocalDateTime;

public record DailyWorkProgressResponse(
        boolean visible,
        String roleType,
        LocalDate date,
        long completed,
        long active,
        long total,
        int percent,
        boolean checked,
        LocalDateTime firstCompletedAt,
        LocalDateTime lastCompletedAt,
        long averageCloseSeconds,
        long medianCloseSeconds,
        long p90CloseSeconds,
        LocalDateTime firstActivityAt,
        LocalDateTime lastActivityAt,
        long activeWorkSeconds,
        long workWindowSeconds,
        long activityEvents,
        long loadScore,
        int efficiencyScore,
        long openedCount,
        long orderCompletedCount,
        long nagulCompletedCount,
        long publishCompletedCount,
        long badCompletedCount,
        long recoveryCompletedCount,
        long recoveryCreatedCount,
        long orderOverdueCount,
        long totalOverdueCount,
        int speedScore,
        int disciplineScore,
        int workloadScore,
        long botChangeCount,
        long botBlockCount,
        boolean reached100,
        LocalDateTime firstReached100At,
        LocalDateTime lastReached100At,
        String periodType,
        int workingDays,
        int checkedDays,
        int reached100Days,
        boolean closedPeriod
) {
    public DailyWorkProgressResponse(
            boolean visible,
            String roleType,
            LocalDate date,
            long completed,
            long active,
            long total,
            int percent,
            boolean checked,
            LocalDateTime firstCompletedAt,
            LocalDateTime lastCompletedAt,
            long averageCloseSeconds,
            long medianCloseSeconds,
            long p90CloseSeconds,
            LocalDateTime firstActivityAt,
            LocalDateTime lastActivityAt,
            long activeWorkSeconds,
            long workWindowSeconds,
            long activityEvents,
            long loadScore,
            int efficiencyScore
    ) {
        this(
                visible,
                roleType,
                date,
                completed,
                active,
                total,
                percent,
                checked,
                firstCompletedAt,
                lastCompletedAt,
                averageCloseSeconds,
                medianCloseSeconds,
                p90CloseSeconds,
                firstActivityAt,
                lastActivityAt,
                activeWorkSeconds,
                workWindowSeconds,
                activityEvents,
                loadScore,
                efficiencyScore,
                total,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                false,
                null,
                null,
                "DAY",
                0,
                0,
                0,
                false
        );
    }

    public static DailyWorkProgressResponse hidden(String roleType, LocalDate date) {
        return new DailyWorkProgressResponse(
                false,
                roleType,
                date,
                0,
                0,
                0,
                0,
                false,
                null,
                null,
                0,
                0,
                0,
                null,
                null,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                false,
                null,
                null,
                "DAY",
                0,
                0,
                0,
                false
        );
    }
}
