package com.hunt.otziv.manager.dto.api;

import java.util.List;

public record CompanyEditResponse(
        Long id,
        String title,
        String urlChat,
        String groupId,
        Long telegramGroupChatId,
        Long maxGroupChatId,
        String urlSite,
        String telephone,
        String city,
        String email,
        String phones,
        String mobilePhones,
        String whatsappPhones,
        String emails,
        String websites,
        String vkUrl,
        String telegramUrl,
        String region,
        String address,
        String industries,
        String companyType,
        String commentsCompany,
        boolean active,
        boolean publicationProgressReportsEnabled,
        String createDate,
        String updateStatus,
        String dateNewTry,
        OptionResponse status,
        OptionResponse category,
        OptionResponse subCategory,
        OptionResponse manager,
        List<OptionResponse> categories,
        List<OptionResponse> subCategories,
        List<OptionResponse> statuses,
        List<OptionResponse> managers,
        List<OptionResponse> workers,
        List<OptionResponse> currentWorkers,
        List<FilialResponse> filials,
        List<OptionResponse> cities,
        boolean canChangeManager
) {
}
