package com.hunt.otziv.worker_activity.model;

public enum WorkerRiskEventType {
    INCIDENT_CREATED,
    EXPLANATION_REQUEST_SENT,
    EXPLANATION_REQUEST_FAILED,
    EXPLANATION_REMINDER_SENT,
    EXPLANATION_RECEIVED,
    EXPLANATION_ASSESSED,
    CLARIFICATION_REQUESTED,
    MANUAL_REVIEW_REQUIRED,
    SPECIALIST_SECTION_RESTRICTED,
    SPECIALIST_SECTION_RELEASED,
    MANAGER_DECISION,
    ADMIN_OVERRIDE,
    INCIDENT_REOPENED,
    AUDIT_REVIEWED
}
