package com.hunt.otziv.worker_activity.model;

public enum WorkerActivityAction {
    REVIEW_COPY_LOGIN,
    REVIEW_COPY_PASSWORD,
    REVIEW_PUBLISH,
    REVIEW_NAGUL,
    REVIEW_BOT_CHANGE,
    REVIEW_BOT_DEACTIVATE,
    REVIEW_TEXT_UPDATE,
    REVIEW_ANSWER_UPDATE,
    REVIEW_NOTE_UPDATE,
    ORDER_NOTE_UPDATE,
    COMPANY_NOTE_UPDATE,
    BAD_TASK_COMPLETE,
    BAD_TASK_UPDATE,
    BAD_TASK_BOT_CHANGE,
    BAD_TASK_BOT_DEACTIVATE,
    RECOVERY_TASK_COMPLETE,
    RECOVERY_TASK_UPDATE,
    RECOVERY_TASK_BOT_CHANGE,
    RECOVERY_TASK_BOT_DEACTIVATE
}
